# Generated by Django 3.2.4 on 2021-06-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210612_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
        ),
    ]
