# Generated by Django 3.2.4 on 2021-06-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-id',)},
        ),
    ]
