# Generated by Django 3.2.4 on 2021-06-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
    ]
